### ISSUE TITLE
Security definitions

### ISSUE THREAD

**Issue by pkupilas** [HoS0/SwaggerMerge#3]
Hey it's me again : )
I have a situation when _securityDefinitions_ for all swagger files are empty:
`{
  "swagger": "2.0",
  "info": {
    "title": "Web API Swagger specification",
    "version": "1.0.0"
  },
  "schemes": [],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    //...
  },
  "definitions": {
    //...
  },
  "responses": {},
  "securityDefinitions": {} //empty
}`
and after merging it this option is coping too even it's empty. 
In fact of that the output page looks like
![swaggersecurity](http://oi65.tinypic.com/1zz6bth.jpg)
Is it a possibility not to copy this parameter if it's empty or customize it (turn on/off coping empty parameters)?

**Comment by alikh31** [comment]
@pkupilas sure it is possible :)
