### ISSUE TITLE
Warning on collision

### ISSUE THREAD

**Issue by loong** [HoS0/SwaggerMerge#4]
Hi there!

First of all thanks for creating this package! Our team is using it in development to pull together all swagger files form our microservices. We want to use this package in production soon, however, we have found a serious problem:

If there are 2 swagger files which maps to the same endpoint name, they overwrite each other. In a bigger team this could make some problems, as people may accidentally reserve the same endpoint name. We use the merged swagger file to automatically define our proxy endpoints, so an  silent overwrite like this could be really hard to debug.

So I hope your package could throw some warnings if there are endpoint collisions.

Let me know what you think!
Long Hoang

**Comment by loong** [comment]
P.S. Same might also apply to the collision of same Resource names.

**Comment by alikh31** [comment]
@mindworker agreed, swagger_merger object should emit warnings in case of collision.

``` javascript
var swaggermerge = require('swagger-merge')
// happens in case of collision in security definitions, resource definitions and routes

swaggermerge.on('warn', function (msg) {
    console.log(msg) // ex. :: multiple routes with the same name and base path has define in swagger collection: /petstore/pets
})
```

**Comment by mindworker** [comment]
Thanks @alikh31! Just found one issue. If a collision is found, it will warn several times and warns following endpoints even if there are no collisions.

E.g. swagger files have those:

```
/v1/manager
/v2/manager
/v2/manger
/v1/data
/v1/content
```

It will throw the following warnings:
```
multiple routes with the same name and base path has define in swagger collection: /v2/manager
multiple routes with the same name and base path has define in swagger collection: /v1/data
multiple routes with the same name and base path has define in swagger collection: /v1/content
```

**Comment by loong** [comment]
@alikh31 Thanks a lot!
