### ISSUE TITLE
PathTooLongException, directory structure

### ISSUE THREAD

**Issue by pkupilas** [HoS0/SwaggerMerge#5]
Hey! 
I am facing the problem with PathTooLongException.
I have msbuild task which searchs some dll after my project is build. Due to swagger-merge has so long directory structure i get this exception.
Is there any posibility to rearrange directory structure to make it shorter : )?

**Comment by alikh31** [comment]
@pkupilas I believe the reason for this is usage of coffee script and its registrator. thanks for mentioning this.
